### ISSUE TITLE
Использование Key ENTER

### ISSUE THREAD

**Issue by OlegSmoliakov** [psibia/SibiaMacroKeyboard#4]
При использовании Key ENTER, выдает ошибку (запрошенное значение не найдено), вместо этого подходит Return.

**Comment by psibia** [comment]
https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
Вот список всех команд, как будет время, изменю руководство пользователя 
Использовать нужно без префикса VK_
